imports:
    - { resource: parameters.yml }
    - { resource: parameters.php }
    - { resource: press_review.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

    assets:
        json_manifest_path: '%kernel.project_dir%/web/build/manifest.json'


# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        GOOGLE_ANALYTICS_ID: "%google_analytics_id%"
        global_menu_prefix: "%global_menu_prefix%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        server_version: "%doctrine.server_version%"
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

knp_menu:
    twig:
        template: "@AfupBarometre/Default/knp_menu.html.twig"

afup_barometre:
    min_result: "%min_result%"

sensio_framework_extra:
    router:
        annotations: false

webpack_encore:
    # The path where Encore is building the assets - i.e. Encore.setOutputPath()
    output_path: '%kernel.project_dir%/web/build'
      # If multiple builds are defined (as shown below), you can disable the default build:
      # output_path: false

      # if using Encore.enableIntegrityHashes() and need the crossorigin attribute (default: false, or use 'anonymous' or 'use-credentials')
      # crossorigin: 'anonymous'

      # preload all rendered script and link tags automatically via the http2 Link header
      # preload: true

      # Throw an exception if the entrypoints.json file is missing or an entry is missing from the data
      # strict_mode: false

      # if you have multiple builds:
      # builds:
      # pass "frontend" as the 3rg arg to the Twig functions
      # {{ encore_entry_script_tags('entry1', null, 'frontend') }}

    # frontend: '%kernel.project_dir%/public/frontend/build'

    # Cache the entrypoints.json (rebuild Symfony's cache when entrypoints.json changes)
    # Put in config/packages/prod/webpack_encore.yaml
    # cache: true
